
export const INCREMENT = 'INCREMENT'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const FILTER_ARTICLE = 'FILTER_ARTICLE'
export const CHANGE_SELECT = 'CHANGE_SELECT'
export const CHANGE_DATE_PICKER = 'CHANGE_DATE_PICKER'